services:
  amplify-json:
    build:
      context: .
      dockerfile: Dockerfile
    image: cabreraevil/amplify-json:latest
    container_name: amplify-json
    labels:
      - "traefik.http.services.amplify-json.loadbalancer.server.port=80"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./public:/app/public:rw
      - ./.aws:/root/.aws:ro
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true
