services:
  amplify-json:
    build:
      context: .
      dockerfile: Dockerfile
    image: cabreraevil/amplify-json:latest
    container_name: amplify-json
    restart: unless-stopped
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws:ro
      - amplify-json-data:/app/public:rw

volumes:
  amplify-json-data:
    driver: local
    name: amplify-json-data
