name: Semantic Release
description: |
  Automated release process using Semantic Release

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write

jobs:
  release:
    name: Release
    uses: cabrera-evil/workflows/.github/workflows/semantic-release.yaml@master
    secrets: inherit
